micronaut:
  application:
    name: casaDoCodigoMicronaut
datasources:
  default:
    url: jdbc:mysql://localhost:3306/casa-do-codigo-micronaut?serverTimezone=UTC
    # driverClassName: com.mysql.jdbc.Driver
    username: eduardo
    password: password
    dialect: MySQL8Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update