spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curso_spring_data?serverTimezone=UTC
    username: root
    password: s2ledzep
    testWhileIdle: true
    validationQuery: SELECT 1
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

