apiVersion: v1
kind: Service
metadata:
  name: svc-pod1
spec:
  type: NodePort
  ports: 
    - port: 80 # Porta para acesso de dentro do cluster
      targetPort: 80 # Porta do node que ele está acessando
      nodePort: 30000 # Porta para acesso de fora do cluster
  selector:
    app: primeiro-pod